"""
Builds spell-text.js: the full rules text shown on the spell card after a win.

Source (clone it next to the project, then run the script):
  git clone --depth 1 https://github.com/5e-bits/5e-database.git   # SRD 5.1 spells (CC BY 4.0)

  python tools/build_spell_text.py

Only SRD 5.1 spells get text: description, "At Higher Levels" and material
components. Spells from other books have no rules text (the card shows their
stats and says which book to find them in). Entries are keyed by the game's
spell name from spells.js, so SRD renames (Arcane Hand -> Bigby's Hand) match.
The text keeps the source's light Markdown (**bold**, tables); game.js
formats it. The game loads this file only when the card is first needed.
"""
import json, re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRD_FILE = ROOT / "5e-database/src/2014/en/5e-SRD-Spells.json"
SPELLS_JS = ROOT / "spells.js"
OUT = ROOT / "spell-text.js"

ABILITIES = "strength|dexterity|constitution|intelligence|wisdom|charisma"


def norm(name):
    return re.sub(r"[^a-z]", "", name.lower())


def tidy(text):
    # the source writes some ability names in lower case ("a dexterity saving throw")
    return re.sub(rf"\b({ABILITIES})\b(?= (?:saving throw|check|modifier|score))",
                  lambda m: m.group(1).capitalize(), text)


def main():
    game = json.loads(re.search(r"=\s*(\[.*\])\s*;?\s*$", SPELLS_JS.read_text(encoding="utf-8"), re.S).group(1))
    names = {}
    for s in game:
        for n in [s["name"], *s["aliases"]]:
            names[norm(n)] = s["name"]

    text, missing = {}, []
    for s in json.loads(SRD_FILE.read_text(encoding="utf-8")):
        name = names.get(norm(s["name"]))
        if not name:
            missing.append(s["name"])
            continue
        entry = {"desc": [tidy(p) for p in s["desc"]]}
        if s.get("higher_level"):
            entry["higher"] = [tidy(p) for p in s["higher_level"]]
        if s.get("material"):
            entry["material"] = s["material"].rstrip(".")
        text[name] = entry

    OUT.write_text(
        "// Generated by tools/build_spell_text.py - do not edit by hand.\n"
        "// Spell descriptions from the System Reference Document 5.1 by Wizards of the Coast LLC, CC BY 4.0.\n"
        f"const SPELL_TEXT = {json.dumps(text, ensure_ascii=False, separators=(',', ':'))};\n",
        encoding="utf-8")
    print(f"{OUT.name}: {len(text)} spells, {OUT.stat().st_size // 1024} KB")
    if missing:
        print("SRD spells with no match in spells.js:", ", ".join(missing))


if __name__ == "__main__":
    main()
