"""
Builds spells.js from the SRD 5.1 spell list in the open-source 5e-database project.

Usage (from the project folder):
    git clone --depth 1 https://github.com/5e-bits/5e-database.git
    python tools/build_spells.py 5e-database/src/2014/en/5e-SRD-Spells.json

It writes spells.js next to index.html. You only need to rerun this if you
change how spells are converted (e.g. add a new column).
"""
import json, re, sys
from pathlib import Path

SRC = Path(sys.argv[1] if len(sys.argv) > 1 else "5e-database/src/2014/en/5e-SRD-Spells.json")
OUT = Path(__file__).resolve().parent.parent / "spells.js"

DAMAGE_TYPES = ["acid", "bludgeoning", "cold", "fire", "force", "lightning", "necrotic",
                "piercing", "poison", "psychic", "radiant", "slashing", "thunder"]
ABILITIES = {"strength": "STR", "dexterity": "DEX", "constitution": "CON",
             "intelligence": "INT", "wisdom": "WIS", "charisma": "CHA"}

def seconds(text):
    """Turn '10 minutes' / '1 round' / '7 days' into seconds, for higher/lower arrows."""
    m = re.match(r"(\d+)\s+(round|minute|hour|day)s?", text.lower())
    if not m:
        return None
    n, unit = int(m.group(1)), m.group(2)
    return n * {"round": 6, "minute": 60, "hour": 3600, "day": 86400}[unit]

def casting_time(raw):
    t = raw.lower()
    if t in ("1 action", "1 bonus action", "1 reaction"):
        label = {"1 action": "Action", "1 bonus action": "Bonus action", "1 reaction": "Reaction"}[t]
        return label, 0          # all "in combat" casts share rank 0: no arrow between them
    return raw, seconds(raw)

def range_ft(raw):
    r = raw.lower()
    if r == "self":  return 0
    if r == "touch": return 1
    if r == "sight": return 10**7
    if r == "unlimited": return 10**9
    m = re.match(r"(\d+)\s+(feet|foot|mile|miles)", r)
    if m:
        n = int(m.group(1))
        return n * 5280 if m.group(2).startswith("mile") else n
    return None                  # "Special": no arrows

def duration(raw):
    label = re.sub(r"^up to\s+", "", raw, flags=re.I)
    label = label[0].upper() + label[1:]
    low = label.lower()
    if low == "instantaneous":       rank = 0
    elif low.startswith("until dispelled"): rank = 10**12
    else:                            rank = seconds(label)
    return label, rank

def effects(s, text):
    dmg = {d["damage_type"]["name"] for d in s.get("damage", []) if "damage_type" in d}
    for t in DAMAGE_TYPES:
        if re.search(rf"\d+d\d+[^.]*?\b{t} damage", text, re.I):
            dmg.add(t.capitalize())
    save = set()
    if s.get("dc"):
        save.add(f'{s["dc"]["dc_type"]["name"]} save')
    for word, abbr in ABILITIES.items():
        if re.search(rf"\b{word} saving throw", text, re.I):
            save.add(f"{abbr} save")
    if s.get("attack_type"):
        save.add(f'{s["attack_type"].capitalize()} attack')
    for kind in ("melee", "ranged"):
        if re.search(rf"\b{kind} spell attack", text, re.I):
            save.add(f"{kind.capitalize()} attack")
    return sorted(dmg) or ["None"], sorted(save) or ["None"]

def clue(s, text):
    """First ~25 words of the description with the spell's own name blanked out."""
    first = s["desc"][0]
    words = first.split()
    snippet = " ".join(words[:25]) + ("…" if len(words) > 25 else "")
    return re.sub(re.escape(s["name"]), "▒▒▒▒", snippet, flags=re.I)

# Hand fixes where the automatic extraction reads the rules text too literally.
# Add entries here if players report a column that feels wrong.
OVERRIDES = {
    "Wish": {"damage": ["None"]},   # the necrotic damage is the caster's stress, not the spell's effect
}

spells = []
for s in json.load(open(SRC, encoding="utf-8")):
    text = " ".join(s["desc"] + s.get("higher_level", []))
    ct_label, ct_rank = casting_time(s["casting_time"])
    du_label, du_rank = duration(s["duration"])
    damage, save = effects(s, text)
    tags = [t for t, on in (("Concentration", s["concentration"]), ("Ritual", s["ritual"])) if on]
    spells.append({
        "name": s["name"],
        "level": s["level"],
        "school": s["school"]["name"],
        "castingTime": ct_label, "castingRank": ct_rank,
        "range": s["range"], "rangeFt": range_ft(s["range"]),
        "components": s["components"],
        "duration": du_label, "durationRank": du_rank,
        "tags": tags or ["Neither"],
        "classes": sorted(c["name"] for c in s["classes"]),
        "damage": damage,
        "save": save,
        "clue": clue(s, text),
    })

for sp in spells:
    sp.update(OVERRIDES.get(sp["name"], {}))

spells.sort(key=lambda x: x["name"])
OUT.write_text(
    "// Generated by tools/build_spells.py from the SRD 5.1 — do not edit by hand.\n"
    "const SPELLS = " + json.dumps(spells, ensure_ascii=False, indent=0) + ";\n",
    encoding="utf-8")
print(f"Wrote {len(spells)} spells to {OUT}")
